In [3]:
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier
import pickle

In [16]:
data = pd.read_csv("Train_telco.csv")
data
data = data.iloc[:,1:]
data

gender  SeniorCitizen  Partner  Dependents  Tenure  PhoneService  \
0          0              0        1           0       1             0   
1          1              0        0           0      34             1   
2          1              0        0           0       2             1   
3          1              0        0           0      45             0   
4          0              0        0           0       2             1   
...      ...            ...      ...         ...     ...           ...   
7006       0              0        0           0      51             1   
7007       0              0        1           1      72             1   
7008       0              0        1           1      11             0   
7009       1              1        1           0       4             1   
7010       1              0        0           0      66             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
0                 0                1               0             1   
1                 0                1               1             0   
2                 0                1               1             1   
3                 0                1               1             0   
4                 0                2               0             0   
...             ...              ...             ...           ...   
7006              0                0               2             2   
7007              1                2               0             1   
7008              0                1               1             0   
7009              1                2               0             0   
7010              0                2               1             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
0                    0            0            0                0         0   
1                    1            0            0                0         1   
2                    0            0            0                0         0   
3                    1            1            0                0         1   
4                    0            0            0                0         0   
...                ...          ...          ...              ...       ...   
7006                 2            2            2                2         2   
7007                 1            0            1                1         1   
7008                 0            0            0                0         0   
7009                 0            0            0                0         0   
7010                 1            1            1                1         2   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
0                    1              2           29.85         29.85      0  
1                    0              3           56.95       1889.50      0  
2                    1              3           53.85        108.15      1  
3                    0              0           42.30       1840.75      0  
4                    1              2           70.70        151.65      1  
...                ...            ...             ...           ...    ...  
7006                 0              0           20.65       1020.75      0  
7007                 1              1          103.20       7362.90      0  
7008                 1              2           29.60        346.45      0  
7009                 1              3           74.40        306.60      1  
7010                 1              0          105.65       6844.50      0  

[7011 rows x 20 columns]

In [18]:
# Establish target feature, churn
y = data.Churn.values
# Drop the target feature from remaining features
X = data.drop('Churn', axis = 1)
# Save dataframe column titles to list, we will need them in next step
cols = X.columns
cols

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'Tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges'],
      dtype='object')

In [19]:
# Import the necessary sklearn method
from sklearn.preprocessing import MinMaxScaler
# Instantiate a Min-Max scaling object
mm = MinMaxScaler()
# Fit and transform our feature data into a pandas dataframe
X = pd.DataFrame(mm.fit_transform(X))

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = .25, random_state = 33)

In [21]:
from sklearn.linear_model import LogisticRegression
# Instantiate a logistic regression model without an intercept, arbitrarily large C value will offset the lack of intercept
logreg = LogisticRegression(fit_intercept = False, C = 1e12, solver 
= 'liblinear')
# Fit the model to our X and y training sets
logreg.fit(X_train, y_train)

LogisticRegression(C=1000000000000.0, fit_intercept=False, solver='liblinear')

In [28]:
y_hat_train = logreg.predict(X_train)
y_hat_test = logreg.predict(X_test)

y_hat_train
y_train

array([0, 1, 0, ..., 0, 1, 1])

In [31]:
import numpy as np

# Find residual differences between train data and predicted train data
residuals = np.abs(y_train, y_hat_train)
residuals

array([0, 1, 0, ..., 0, 1, 1])

In [32]:

# Print the number of times our model was correct ('0') and incorrect ('1')
print(pd.Series(residuals).value_counts())
# Print normalized amount of times our model was correct (percentage)
print(pd.Series(residuals).value_counts(normalize = True))

0    3862
1    1396
dtype: int64
0    0.7345
1    0.2655
dtype: float64


In [34]:
from sklearn.metrics import confusion_matrix
# Pass actual test and predicted target test outcomes to function
cnf_matrix = confusion_matrix(y_test, y_hat_test)
cnf_matrix

array([[1147,  138],
       [ 212,  256]])

In [35]:
import pickle
with open('model_pkl', 'wb') as files:
    pickle.dump(logreg, files)